import ClientProviderWrapper from '../ClientProviderWrapper';
import type { Metadata } from 'next';
import '../globals.css';
import { dir } from 'i18next';
import { i18n } from '../../../next-i18next.config';

export const metadata: Metadata = {
  title: 'REST Client',
  description: 'Generated by create next app',
  icons: { icon: '/fav.ico' },
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  const locale = i18n.locales.includes(params.lang)
    ? params.lang
    : i18n.defaultLocale;

  return (
    <html lang={locale} dir={dir(locale)}>
      <body>
        <ClientProviderWrapper> {children}</ClientProviderWrapper>
      </body>
    </html>
  );
}
