import ClientProviderWrapper from './ClientProviderWrapper';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'REST Client',
  description: 'Generated by create next app',
  icons: { icon: '/fav.ico' },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProviderWrapper>{children}</ClientProviderWrapper>
      </body>
    </html>
  );
}
