import { ReactNode } from 'react';
import ClientProviderWrapper from './ClientProviderWrapper';
import type { Metadata } from 'next';
import './globals.css';
import '../i18';

export const metadata: Metadata = {
  title: 'REST Client',
  description: 'Generated by create next app',
  icons: { icon: '/fav.ico' },
};

export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params?: { locale?: string };
}) {
  const locale = params?.locale ?? 'en';

  return (
    <html lang={locale}>
      <body>
        <ClientProviderWrapper>{children}</ClientProviderWrapper>
      </body>
    </html>
  );
}
