import ClientProviderWrapper from './ClientProviderWrapper';
import type { Metadata } from 'next';
import './globals.css';
import '../i18';

export const metadata: Metadata = {
  title: 'REST Client',
  description: 'Generated by create next app',
  icons: { icon: '/fav.ico' },
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params?: Record<string, string> | Promise<Record<string, string>>;
}) {
  const resolvedParams = params ? await params : {};
  const locale = resolvedParams.locale ?? 'en';

  return (
    <html lang={locale}>
      <body>
        <ClientProviderWrapper>{children}</ClientProviderWrapper>
      </body>
    </html>
  );
}
